name: Deploy

on:
  push:
    branches:
      - main  # Prueba de deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy message
        run: echo "Listo para desplegar"